version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  notify-success:
    docker:
      - image: alpine:3.14
    steps:
      - run:
          name: Send success notification
          command: echo "Tests passed successfully"

workflows:
  version: 2
  build-and-notify:
    jobs:
      - build
      - notify-success:
          requires:
            - build
